#!/usr/bin/env bash
# Transfer a file from client to server
if [ "$#" -le 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    user=$3"@"$2":~/."
    scp -oStrictHostKeyChecking=no -i$4 $1 "$user"
fi
