#!/usr/bin/env bash
# Install nginx server and change index.html page to show text, Holberton School
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
orig="location / {\n\ttry_files $uri $uri/ =404;\n}"
new="location / {\n\ttry_files $uri $uri/ =404;\n}\n\nlocation /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sed -i "s/$orig/$new/" /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo service nginx start
