#!/usr/bin/env bash
# Create custom 404 page with string, Ceci n'est pas une page.

apt-get update
apt-get -y install nginx
new="server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;
        }

        location /redirect_me {
                 return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        #error_page 404 /404.html;
        location = /404.html {
                 root /usr/share/nginx/html;
                 internal;
        }
}"

echo "$new" > /etc/nginx/sites-available/default
service nginx stop
service nginx start
