#!/usr/bin/env bash
# Redirect an endpoint to another page

apt-get update
apt-get -y install nginx
new="server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        # Add hostname to custom HTTP header
        server_name localhost;
        add_header X-Served-By $hostname;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;
        }

        location /redirect_me {
                 return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"

echo "$new" > /etc/nginx/sites-available/default
service nginx stop
service nginx start
