#!/usr/bin/env bash
# Install and configure HAproxy on load balancing lb-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get update
sudo apt-get -y install haproxy

# sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo service haproxy start
