#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays "To infinity and beyond" indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

#mkdir /var/run/holbertonscript.pid
#chown root:root /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
while true
do
      echo "To infinity and beyond"
      sleep 2
      trap "echo Y U no love me?!" SIGINT
      trap "rm /var/run/holbertonscript.pid" SIGQUIT SIGTERM
      trap "echo I hate the kill command; pkill -9 -f '100-process_and_pid_file'" SIGTERM
done
