#!/usr/bin/env bash
# Display "To infinity and beyond" forever. Print "I am invincible!!!" when SIGTERM received
while true
do
      echo "To infinity and beyond"
      sleep 2
      trap "echo I am invincible!!!" SIGTERM
done
