#!/usr/bin/env bash
# Displays the contents of the file /etc/passwd
# username, group id, & shell full path for the user
if [ -e /etc/passwd ]
then
	grep -w "$1" /etc/passwd | while IFS=':' read U P USRID GID D HOMED SHL
	do
	    echo -e "$U:$GID:$HOMED"
        done
fi
