#!/usr/bin/env bash
# Displays the contents of the file /etc/passwd
# username, group id, & shell full path for the user
input="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d: -f1,4,6
done < "$input"
