#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" once on #9
for i in {1..10};
do
    if [ $i != 9 ];
    then echo "Holberton School";
    else echo "Holberton School"; echo "Hi";
    fi
done
