#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" once on #9
i=0;
while [ $i -lt 10 ];
do
    if [ $i != 9 ];
    then echo "Holberton School";
    else echo "Hi"; echo "Holberton School";
    fi
    (( i++ ))
done
