#!/usr/bin/env bash
# This script displays "bad luck from China" on 4th loop,
# "bad luck from Japan" on 9th loop, and
# the iteration number the other times
i=1;
while [ $i -le 20 ]; do
    echo $i;
    case "$i" in
	4) echo "bad luck from China"
	    ;;
	9) echo "bad luck from Japan"
	    ;;
	17) echo "bad luck from Italy"
	    ;;
    esac
    (( i++ ))
done
