#!/usr/bin/env bash
# This script lists the current directory where
# the name after the first dash is displayed
for i in *;
do
    echo "$i" | cut -s -d'-' -f 1 --complement
    #echo "$i" | cut -d"-" -f1 --complement
    #echo "$i" | awk -F'[-]' '{print $2}'
done
